/* Formatted on 24/11/2015 17:16:52 (QP5 v5.287) */
CREATE TABLE OFFERS
(
   OFFER_ID              NUMBER (10) NOT NULL,
   CATEGORY_ID           NUMBER (10) NOT NULL,
   MIN_QTY_TO_PURCHASE   NUMBER (5),
   COMPANY_ID            NUMBER (20) NOT NULL,
   OFFER_VALUE           NUMBER (10, 4),
   BRAND_ID              NUMBER (10) NOT NULL,
   CONSTRAINT OFFERS_PK PRIMARY KEY (OFFER_ID)
);

CREATE TABLE TRAIN_HISTORY
(
   TRAIN_HISTORY_ID   NUMBER (10) NOT NULL,
   CHAIN_ID           NUMBER (10) NOT NULL,
   OFFER_ID           NUMBER (10) NOT NULL,
   MARKET_ID          NUMBER (10),
   REPEAT_TRIPS       NUMBER (10),
   REPEATER           VARCHAR2 (1),
   OFFER_DATE         DATE
);

CREATE TABLE TRANSACTIONS
(
   TRANSACTION_ID   NUMBER (10) NOT NULL,
   CHAIN_ID         NUMBER (10) NOT NULL,
   DEPARTMENT_ID    NUMBER (10) NOT NULL,
   CATEGORY_ID      NUMBER (10) NOT NULL,
   COMPANY_ID       NUMBER (20) NOT NULL,
   BRAND_ID         NUMBER (10) NOT NULL,
   PURCHASE_DATE    DATE,
   PROD_SIZE        NUMBER (10, 4),
   PROD_MEASURE     VARCHAR2 (20),
   PURCHASE_QTY     NUMBER (10),
   PURCHASE_AMT     NUMBER (10, 4)
);